### ISSUE TITLE
Show manpage is exact match found

### ISSUE THREAD

**Issue by AlekSi** [apophys/SublimeManpage#10]
When I ask plugin to show free() manpage, it proposes a lot of variants, but there is an exact match.

**Comment by apophys** [comment]
First draft in 186b25c.
CC @crazybyte

**Comment by crazybyte** [comment]
@apophys very nice :) Wouldn't be a good idea also to define a key shortcut (and command in the command palette) that would allow the user to change value of the exact_match setting without editing the user settings file. To be clear on what I want to say see the following use case(s):
- user sets the value of exact_match to True and continues on using the plugin
- at one particular time he decides that he want to see the entire list of function (temporarily), this is when the on the fly modification of the exact_match setting would come handy
- another case when the on the fly modification of the exact_match setting would come handy is when the same command has many variants (as in the case of function and command free) and he wants to see lets say the last one from the entire list and the exact_match will stop him to see it (switching to see the entire list would allow him to see the last man page in the list).

What do you think it would be a useful feature or I misread the code and it is a dumb idea?
If you want I could implement it (it's a very simple modification). Thank you!

Best regards,
crazybyte

**Comment by apophys** [comment]
Actually there are several more commits after the one referenced. Exact match can be enabled or disabled from command palette.

As for the key shortcut I probably wouldn't set some default value in this case. User can define his own key binding.

**Comment by crazybyte** [comment]
Ah, I didn't look the other commits (need more coffee).

**Comment by apophys** [comment]
Commited and pushed to sublime as an update.
